{
    "openapi": "3.0.0",
    "info": {
        "title": "Bulls Shop API",
        "description": "API do e-commerce Bulls Shop, projeto de BD2",
        "version": "1.0.0"
    },
    "apis": [
        "./src/server.ts"
    ],
    "servers": [
        {
            "url": "https://projeto-bd2.herokuapp.com",
            "description": "Produção"
        },
        {
            "url": "http://localhost:3000/",
            "description": "local"
        }
    ],
    "paths": {
        "/cidades": {
            "post": {
                "summary": "Cadastro de cidades",
                "tags": ["Cidades"],
                "security": [{ "bearerAuth": [] }],
                "requestBody": {
                    "description": "Corpo da requisição",
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Cidades"
                            },
                            "examples": {
                                "cidade": {
                                    "value": {
                                        "cidade": "cidade",
                                        "estado": 1
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "400": {
                        "description": "Essa cidade já existe!"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Cidades"
                                }
                            }
                        }
                    }
                }
            },
            "get": {
                "summary": "Listagem de cidades",
                "tags": ["Cidades"],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Cidades"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/cidades/{id_cidade}": {
            "put": {
                "summary": "Edição de cidades",
                "tags": ["Cidades"],
                "security": [{ "bearerAuth": [] }],
                "parameters": {
                    "in": "path",
                    "name": "id_cidade",
                    "required": true,
                    "schema": {
                        "type": "number"
                    },
                    "description": "ID da cidade que será editada"
                },
                "requestBody": {
                    "description": "Corpo da requisição",
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Cidades"
                            },
                            "examples": {
                                "cidade": {
                                    "value": {
                                        "cidade": "cidade nova",
                                        "estado": 2
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Cidades"
                                }
                            }
                        }
                    }
                }
            },
            "delete": {
                "summary": "Exclusão de cidade",
                "tags": ["Cidades"],
                "security": [{ "bearerAuth": [] }],
                "parameters": {
                    "in": "path",
                    "name": "id_cidade",
                    "required": true,
                    "schema": {
                        "type": "number"
                    },
                    "description": "ID da cidade que será excluída"
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Cidades"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/categorias": {
            "post": {
                "summary": "Cadastro de categorias",
                "tags": ["Categorias"],
                "security": [{ "bearerAuth": [] }],
                "requestBody": {
                    "description": "Corpo da requisição",
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Categorias"
                            },
                            "examples": {
                                "categoria": {
                                    "value": {
                                        "nome": "Tênis"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "400": {
                        "description": "Essa categoria já existe!"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Categorias"
                                }
                            }
                        }
                    }
                }
            },
            "get": {
                "summary": "Listagem de categorias",
                "tags": ["Categorias"],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Categorias"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/categorias/{id_categoria}": {
            "put": {
                "summary": "Edição de categorias",
                "tags": ["Categorias"],
                "security": [{ "bearerAuth": [] }],
                "parameters": {
                    "in": "path",
                    "name": "id_categoria",
                    "required": true,
                    "schema": {
                        "type": "number"
                    },
                    "description": "ID da categoria que será editada"
                },
                "requestBody": {
                    "description": "Corpo da requisição",
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Categorias"
                            },
                            "examples": {
                                "categoria": {
                                    "value": {
                                        "nome": "Calça"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Categorias"
                                }
                            }
                        }
                    }
                }
            },
            "delete": {
                "summary": "Exclusão de categoria",
                "tags": ["Categorias"],
                "security": [{ "bearerAuth": [] }],
                "parameters": {
                    "in": "path",
                    "name": "id_categoria",
                    "required": true,
                    "schema": {
                        "type": "number"
                    },
                    "description": "ID da categoria que será excluída"
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Categorias"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/compras": {
            "post": {
                "summary": "Cadastro de compra",
                "tags": ["Compras"],
                "requestBody": {
                    "description": "Corpo da requisição",
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Compras"
                            },
                            "examples": {
                                "compra": {
                                    "value": {
                                        "cliente": 1,
                                        "total": 500
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Compras"
                                }
                            }
                        }
                    }
                }
            },
            "get": {
                "summary": "Listagem de compras",
                "tags": ["Compras"],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Compras"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/compras/{id_compra}": {
            "put": {
                "summary": "Edição de compras",
                "tags": ["Compras"],
                "parameters": {
                    "in": "path",
                    "name": "id_compra",
                    "required": true,
                    "schema": {
                        "type": "number"
                    },
                    "description": "ID da compra que será editada"
                },
                "requestBody": {
                    "description": "Corpo da requisição",
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Compras"
                            },
                            "examples": {
                                "compra": {
                                    "value": {
                                        "cliente": 2,
                                        "total": 800
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Compras"
                                }
                            }
                        }
                    }
                }
            },
            "delete": {
                "summary": "Exclusão de compra",
                "tags": ["Compras"],
                "security": [{ "bearerAuth": [] }],
                "parameters": {
                    "in": "path",
                    "name": "id_compra",
                    "required": true,
                    "schema": {
                        "type": "number"
                    },
                    "description": "ID da compra que será excluída"
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Compras"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/estados": {
            "post": {
                "summary": "Cadastro de estados",
                "tags": ["Estados"],
                "security": [{ "bearerAuth": [] }],
                "requestBody": {
                    "description": "Corpo da requisição",
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Estados"
                            },
                            "examples": {
                                "estado": {
                                    "value": {
                                        "estado": "Santa Catarina",
                                        "sigla": "SC"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "400": {
                        "description": "Esse estado já está cadastrado!"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Estados"
                                }
                            }
                        }
                    }
                }
            },
            "get": {
                "summary": "Listagem de estados",
                "tags": ["Estados"],
                "security": [{ "bearerAuth": [] }],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Estados"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/estados/{id_estado}": {
            "put": {
                "summary": "Edição de estados",
                "tags": ["Estados"],
                "security": [{ "bearerAuth": [] }],
                "parameters": {
                    "in": "path",
                    "name": "id_estado",
                    "required": true,
                    "schema": {
                        "type": "number"
                    },
                    "description": "ID do estado que será editado"
                },
                "requestBody": {
                    "description": "Corpo da requisição",
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Estados"
                            },
                            "examples": {
                                "estado": {
                                    "value": {
                                        "estado": "Acre",
                                        "sigla": "AC"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Estados"
                                }
                            }
                        }
                    }
                }
            },
            "delete": {
                "summary": "Exclusão de estado",
                "tags": ["Estados"],
                "security": [{ "bearerAuth": [] }],
                "parameters": {
                    "in": "path",
                    "name": "id_estado",
                    "required": true,
                    "schema": {
                        "type": "number"
                    },
                    "description": "ID do estado que será excluído"
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Estados"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/marcas": {
            "post": {
                "summary": "Cadastro de marcas",
                "tags": ["Marcas"],
                "security": [{ "bearerAuth": [] }],
                "requestBody": {
                    "description": "Corpo da requisição",
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Marcas"
                            },
                            "examples": {
                                "marca": {
                                    "value": {
                                        "marca": "Puma"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "400": {
                        "description": "Essa marca já está cadastrada!"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Marcas"
                                }
                            }
                        }
                    }
                }
            },
            "get": {
                "summary": "Listagem de marcas",
                "tags": ["Marcas"],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Marcas"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/marcas/{id_marca}": {
            "put": {
                "summary": "Edição de marcas",
                "tags": ["Marcas"],
                "security": [{ "bearerAuth": [] }],
                "parameters": {
                    "in": "path",
                    "name": "id_marca",
                    "required": true,
                    "schema": {
                        "type": "number"
                    },
                    "description": "ID da marca que será editada"
                },
                "requestBody": {
                    "description": "Corpo da requisição",
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Marcas"
                            },
                            "examples": {
                                "marca": {
                                    "value": {
                                        "marca": "Topper"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Marcas"
                                }
                            }
                        }
                    }
                }
            },
            "delete": {
                "summary": "Exclusão de marca",
                "tags": ["Marcas"],
                "security": [{ "bearerAuth": [] }],
                "parameters": {
                    "in": "path",
                    "name": "id_marca",
                    "required": true,
                    "schema": {
                        "type": "number"
                    },
                    "description": "ID da marca que será excluída"
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Marcas"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/produtos": {
            "post": {
                "summary": "Cadastro de produtos",
                "tags": ["Produtos"],
                "security": [{ "bearerAuth": [] }],
                "requestBody": {
                    "description": "Corpo da requisição",
                    "required": true,
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "$ref": "#/components/schemas/Produtos"
                            },
                            "examples": {
                                "marca": {
                                    "value": {
                                        "nome": "camiseta esportiva",
                                        "descricao": "camiseta para esportes",
                                        "imagem": "images/camiseta_esportiva.png",
                                        "preco": 200,
                                        "estoque": 20,
                                        "categoria": 1,
                                        "marca": 1,
                                        "imposto": 20
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Produtos"
                                }
                            }
                        }
                    }
                }
            },
            "get": {
                "summary": "Listagem de produtos",
                "tags": ["Produtos"],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Produtos"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/produtos/{id_produto}": {
            "put": {
                "summary": "Edição de produtos",
                "tags": ["Produtos"],
                "security": [{ "bearerAuth": [] }],
                "parameters": {
                    "in": "path",
                    "name": "id_produto",
                    "required": true,
                    "schema": {
                        "type": "number"
                    },
                    "description": "ID do produto que será editado"
                },
                "requestBody": {
                    "description": "Corpo da requisição",
                    "required": true,
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "$ref": "#/components/schemas/Produtos"
                            },
                            "examples": {
                                "marca": {
                                    "value": {
                                        "nome": "camiseta não esportiva",
                                        "descricao": "camiseta para não fazer esportes",
                                        "imagem": "images/camiseta_nao_esportiva.png",
                                        "preco": 10,
                                        "estoque": 20,
                                        "categoria": 1,
                                        "marca": 1,
                                        "imposto": 50
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Produtos"
                                }
                            }
                        }
                    }
                }
            },
            "delete": {
                "summary": "Exclusão de produtos",
                "tags": ["Produtos"],
                "security": [{ "bearerAuth": [] }],
                "parameters": {
                    "in": "path",
                    "name": "id_produto",
                    "required": true,
                    "schema": {
                        "type": "number"
                    },
                    "description": "ID do produto que será excluído"
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Produtos"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/usuarios": {
            "get": {
                "summary": "Listagem de usuários",
                "tags": ["Usuários"],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Usuarios"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/usuarios/{id_usuario}": {
            "put": {
                "summary": "Edição de usuário",
                "tags": ["Usuários"],
                "security": [{ "bearerAuth": [] }],
                "parameters": {
                    "in": "path",
                    "name": "id_usuario",
                    "required": true,
                    "schema": {
                        "type": "number"
                    },
                    "description": "ID do usuário que será editado"
                },
                "requestBody": {
                    "description": "Corpo da requisição",
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Usuarios"
                            },
                            "examples": {
                                "cliente": {
                                    "value": {
                                        "nome": "Valdema",
                                        "email": "valdemar@gmail.com",
                                        "senha": "123456",
                                        "cpf": "12345678900",
                                        "endereco": {
                                            "value": {
                                                "rua": "rua",
                                                "bairro": "bairro",
                                                "numero": "123",
                                                "cidade": 1,
                                                "estado": 1,
                                                "CEP": "12345678"
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Usuarios"
                                }
                            }
                        }
                    }
                }
            },
            "delete": {
                "summary": "Exclusão de usuário",
                "tags": ["Usuários"],
                "security": [{ "bearerAuth": [] }],
                "parameters": {
                    "in": "path",
                    "name": "id_usuario",
                    "required": true,
                    "schema": {
                        "type": "number"
                    },
                    "description": "ID do usuario que será excluído"
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Usuarios"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/cadastrar": {
            "post": {
                "summary": "Cadastro de usuário",
                "tags": ["Autenticação"],
                "requestBody": {
                    "description": "Corpo da requisição",
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Usuarios"
                            },
                            "examples": {
                                "cliente": {
                                    "value": {
                                        "nome": "Valdemar",
                                        "email": "valdemar@gmail.com",
                                        "senha": "123456",
                                        "cpf": "12345678900",
                                        "endereco": {
                                            "value": {
                                                "rua": "rua",
                                                "bairro": "bairro",
                                                "numero": "123",
                                                "cidade": 1,
                                                "estado": 1,
                                                "CEP": "12345678"
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Usuarios"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Usuário já existe!"
                    }
                }
            }
        },
        "/login": {
            "post": {
                "summary": "Login de usuário",
                "tags": ["Autenticação"],
                "requestBody": {
                    "description": "Corpo da requisição",
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "email": {
                                        "type": "string"
                                    },
                                    "senha": {
                                        "type": "string"
                                    }
                                }
                            },
                            "examples": {
                                "cliente": {
                                    "value": {
                                        "email": "teste6@teste6.com",
                                        "senha": "123456"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Usuarios"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Email/Senha incorretos."
                    },
                    "401": {
                        "description": "No token provided"
                    }
                }
            }
        }
    },
    "components": {
        "schemas": {
            "Categorias": {
                "type": "object",
                "properties": {
                    "id_categoria": {
                        "type": "number"
                    },
                    "nome": {
                        "type": "string"
                    }
                }
            },
            "Cidades": {
                "type": "object",
                "properties": {
                    "id_cidade": {
                        "type": "number"
                    },
                    "cidade": {
                        "type": "string"
                    },
                    "estado": {
                        "type": "number"
                    }
                }
            },
            "Compras": {
                "type": "object",
                "properties": {
                    "id_compra": {
                        "type": "number"
                    },
                    "cliente": {
                        "type": "number"
                    },
                    "total": {
                        "type": "number"
                    }
                }
            },
            "Enderecos": {
                "type": "object",
                "properties": {
                    "id_endereco": {
                        "type": "number"
                    },
                    "rua": {
                        "type": "string"
                    },
                    "bairro": {
                        "type": "string"
                    },
                    "numero": {
                        "type": "string"
                    },
                    "cidade": {
                        "type": "number"
                    },
                    "estado": {
                        "type": "number"
                    },
                    "CEP": {
                        "type": "string"
                    }
                }
            },
            "Estados": {
                "type": "object",
                "properties": {
                    "id_estado": {
                        "type": "number"
                    },
                    "estado": {
                        "type": "string"
                    },
                    "sigla": {
                        "type": "string"
                    }
                }
            },
            "Marcas": {
                "type": "object",
                "properties": {
                    "id_marca": {
                        "type": "number"
                    },
                    "marca": {
                        "type": "string"
                    }
                }
            },
            "Produtos": {
                "type": "object",
                "properties": {
                    "id_produto": {
                        "type": "number"
                    },
                    "nome": {
                        "type": "string"
                    },
                    "descricao": {
                        "type": "string"
                    },
                    "file": {
                        "type": "string",
                        "format": "binary"
                    },
                    "preco": {
                        "type": "number"
                    },
                    "estoque": {
                        "type": "number"
                    },
                    "categoria": {
                        "type": "number"
                    },
                    "marca": {
                        "type": "number"
                    },
                    "imposto": {
                        "type": "number"
                    }
                }
            },
            "Usuarios": {
                "type": "object",
                "properties": {
                    "id_cliente": {
                        "type": "number"
                    },
                    "nome": {
                        "type": "string"
                    },
                    "email": {
                        "type": "string"
                    },
                    "senha": {
                        "type": "string"
                    },
                    "cpf": {
                        "type": "string"
                    },
                    "endereco": {
                        "type": "object",
                        "$ref": "#/components/schemas/Enderecos"
                    },
                    "admin": {
                        "type": "number"
                    }
                }
            }
        }
    },
    "securitySchemes": {
        "bearerAuth": {
            "type": "http",
            "scheme": "bearer",
            "bearerFormat": "JWT"
        }
    }
}